import type { Product } from './ProductCard'

export const PRODUCTS: Product[] = [
  /* ── BOUQUETS ── */
  {
    id: 1, slug: 'bouquet-signature-rosa',
    name: 'Bouquet Signature Rosa — M',
    category: 'bouquets', price: 55, rating: 4.9, reviews: 214,
    image: 'https://images.unsplash.com/photo-1490750967868-88df5691cc0b?w=600&q=75&auto=format',
    badge: 'Best-seller', badgeColor: '#B5275C',
    occasion: ['anniversaire', 'saint-valentin', 'amour'],
    inStock: true, sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 2, slug: 'bouquet-pivoine-eternel',
    name: 'Bouquet Pivoine Éternel — L',
    category: 'bouquets', price: 89, rating: 4.8, reviews: 138,
    image: 'https://images.unsplash.com/photo-1561181286-d3fee7d55364?w=600&q=75&auto=format',
    badge: 'Coup de cœur', badgeColor: '#C9A84C',
    occasion: ['anniversaire', 'mariage', 'amour'],
    inStock: true, isNew: false, sizes: ['M', 'L', 'XL'],
  },
  {
    id: 3, slug: 'bouquet-blanc-elegance',
    name: 'Bouquet Blanc Élégance',
    category: 'bouquets', price: 65, rating: 4.7, reviews: 91,
    image: 'https://images.unsplash.com/photo-1455659817273-f96807779a8a?w=600&q=75&auto=format',
    occasion: ['mariage', 'naissance', 'remerciement'],
    inStock: true, sizes: ['S', 'M', 'L'],
  },
  {
    id: 4, slug: 'bouquet-tropical-paradise',
    name: 'Bouquet Tropical Paradise',
    category: 'bouquets', price: 72, oldPrice: 85, rating: 4.6, reviews: 63,
    image: 'https://images.unsplash.com/photo-1487530811015-780d6e78a5d9?w=600&q=75&auto=format',
    occasion: ['anniversaire', 'amour'],
    inStock: true, isNew: true,
  },
  {
    id: 5, slug: 'bouquet-saint-valentin-xxl',
    name: 'Bouquet Saint-Valentin XXL',
    category: 'bouquets', price: 110, rating: 5.0, reviews: 47,
    image: 'https://images.unsplash.com/photo-1562690868-60bbe7293e94?w=600&q=75&auto=format',
    badge: 'Édition limitée', badgeColor: '#B5275C',
    occasion: ['saint-valentin', 'amour'],
    inStock: true, sizes: ['XL', 'XXL'],
  },
  {
    id: 6, slug: 'bouquet-automne-dore',
    name: 'Bouquet Automne Doré',
    category: 'bouquets', price: 48, rating: 4.5, reviews: 82,
    image: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=600&q=75&auto=format',
    occasion: ['anniversaire', 'remerciement'],
    inStock: true,
  },
  {
    id: 7, slug: 'bouquet-roses-rouges-classique',
    name: 'Bouquet Roses Rouges Classique',
    category: 'bouquets', price: 59, rating: 4.8, reviews: 176,
    image: 'https://images.unsplash.com/photo-1550159930-40066082a4fc?w=600&q=75&auto=format',
    occasion: ['saint-valentin', 'amour', 'anniversaire'],
    inStock: true,
  },

  /* ── PELUCHES ── */
  {
    id: 8, slug: 'ours-caramel-grand-80cm',
    name: 'Ours Caramel Grand — 80cm',
    category: 'peluches', price: 49, rating: 4.9, reviews: 203,
    image: 'https://images.unsplash.com/photo-1584464491033-06628f3a6b7b?w=600&q=75&auto=format',
    badge: 'Best-seller', badgeColor: '#B5275C',
    occasion: ['anniversaire', 'naissance', 'saint-valentin'],
    inStock: true,
  },
  {
    id: 9, slug: 'ours-rose-geant-1m',
    name: 'Ours Rose Géant — 1m',
    category: 'peluches', price: 129, rating: 4.7, reviews: 54,
    image: 'https://images.unsplash.com/photo-1559715745-e1b33a271c8f?w=600&q=75&auto=format',
    badge: 'Coup de cœur', badgeColor: '#C9A84C',
    occasion: ['anniversaire', 'saint-valentin'],
    inStock: true, isNew: false,
  },
  {
    id: 10, slug: 'lapin-blanc-peluche-50cm',
    name: 'Lapin Blanc Doudou — 50cm',
    category: 'peluches', price: 35, rating: 4.8, reviews: 89,
    image: 'https://images.unsplash.com/photo-1581385339821-5b358673a883?w=600&q=75&auto=format',
    occasion: ['naissance', 'anniversaire'],
    inStock: true, isNew: true,
  },
  {
    id: 11, slug: 'panda-geant-90cm',
    name: 'Panda Géant Bamboue — 90cm',
    category: 'peluches', price: 89, oldPrice: 110, rating: 4.6, reviews: 41,
    image: 'https://images.unsplash.com/photo-1517191434949-5e90cd67d2b6?w=600&q=75&auto=format',
    occasion: ['anniversaire', 'saint-valentin'],
    inStock: true,
  },
  {
    id: 12, slug: 'licorne-arc-en-ciel-60cm',
    name: 'Licorne Arc-en-ciel — 60cm',
    category: 'peluches', price: 42, rating: 4.9, reviews: 127,
    image: 'https://images.unsplash.com/photo-1558171813-4882e4cbf3e9?w=600&q=75&auto=format',
    occasion: ['anniversaire', 'naissance'],
    inStock: true, isNew: true,
  },

  /* ── CHOCOLATS ── */
  {
    id: 13, slug: 'coffret-ganaches-maison',
    name: 'Coffret Ganaches Maison — 16 pcs',
    category: 'chocolats', price: 24, rating: 4.8, reviews: 156,
    image: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&q=75&auto=format',
    badge: 'Artisanal', badgeColor: '#8B5E3C',
    occasion: ['anniversaire', 'remerciement', 'saint-valentin'],
    inStock: true,
  },
  {
    id: 14, slug: 'box-truffes-noir-blanc',
    name: 'Box Truffes Noir & Blanc — 20 pcs',
    category: 'chocolats', price: 38, rating: 4.9, reviews: 72,
    image: 'https://images.unsplash.com/photo-1606312619070-d48b6b4c8365?w=600&q=75&auto=format',
    badge: 'Coup de cœur', badgeColor: '#C9A84C',
    occasion: ['anniversaire', 'saint-valentin', 'mariage'],
    inStock: true,
  },
  {
    id: 15, slug: 'tablettes-grand-cru-3pcs',
    name: 'Tablettes Grand Cru — 3 pcs',
    category: 'chocolats', price: 22, rating: 4.7, reviews: 98,
    image: 'https://images.unsplash.com/photo-1511381939415-e44015466834?w=600&q=75&auto=format',
    occasion: ['remerciement', 'anniversaire'],
    inStock: true,
  },
  {
    id: 16, slug: 'coffret-pralines-luxe',
    name: 'Coffret Pralinés Luxe — 32 pcs',
    category: 'chocolats', price: 58, oldPrice: 68, rating: 4.8, reviews: 44,
    image: 'https://images.unsplash.com/photo-1571506165871-ee72a35bc9d4?w=600&q=75&auto=format',
    badge: 'Promo', badgeColor: '#EF4444',
    occasion: ['anniversaire', 'mariage', 'noel'],
    inStock: true, isNew: false,
  },
  {
    id: 17, slug: 'mendiants-artisanaux-200g',
    name: 'Mendiants Artisanaux — 200g',
    category: 'chocolats', price: 18, rating: 4.6, reviews: 61,
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&q=75&auto=format',
    occasion: ['remerciement', 'noel'],
    inStock: true, isNew: true,
  },
]
